### PR TITLE
Issues

### PR DESCRIPTION
**Pull request by 6nv**
Add your issues, feature requests, and bug reports here in this thread.

### CODE REVIEW

**Comment by 6nv** [comment]
## Bug:
When plugin is packaged, it doubles-up on packaging the gradient icons.

**Comment by 6nv** [comment]
> ## Bug:
> When plugin is packaged, it doubles-up on packaging the gradient icons.

Fixed in 766dfafdaaf6c6b9f7c6e1c9654c96eaa41ca682

**Comment by 6nv** [comment]
a

**Comment by 6nv** [comment]
## Update:

There are too many screenshots, and some are outdated. Update screenshots.

**Comment by yevgeny7** [comment]
### Feature Request:
Many European countries use a mirrored version of the psychrometric chart, with temperature on y-axis, absolute humidity on x-axis, and obviously SI units. We call it "Mollier-hx-Diagramm". The content is the same.
[Example Wikipedia](https://de.wikipedia.org/wiki/Mollier-h-x-Diagramm)
It would be a super feature if it was possible to chose this "European version".
The plugin right now is awesome, but unfortunately not much of a help in my country as this sort of diagram is unknown.

**Comment by 6nv** [comment]
> [yevgeny7](https://github.com/yevgeny7) commented [11 minutes ago](https://github.com/nicfv/Psychart/pull/11#issuecomment-1984041819)
> ### Feature Request:
> Many European countries use a mirrored version of the psychrometric chart, with temperature on y-axis, absolute humidity on x-axis, and obviously SI units. We call it "Mollier-hx-Diagramm". The content is the same. [Example Wikipedia](https://de.wikipedia.org/wiki/Mollier-h-x-Diagramm) It would be a super feature if it was possible to chose this "European version". The plugin right now is awesome, but unfortunately not much of a help in my country as this sort of diagram is unknown.

Hi @yevgeny7 and thanks for your request! I don't think this type of chart is as common in the United States, but I am familiar with it and think it would be a great addition for Psychart. I'll keep you updated when I am able to work on this.

**Comment by 6nv** [comment]
@yevgeny7 I'm working on cleaning things up and fixing some issues in version 4.2.x. Version 4.3.x will probably be a minor version where I update Grafana dependencies to the latest Grafana version, and your feature is something I'd like to introduce in the following minor version, 4.4.x. I'm hoping to get to that point within the next few weeks, and I'll let you know when it's actively in development!

**Comment by 6nv** [comment]
> [yevgeny7](https://github.com/yevgeny7) commented [last month](https://github.com/nicfv/Psychart/pull/11#issuecomment-2014593731)
>
> @6nv Sounds great. I'm happy to help with some testing and feedback.

Thanks for your patience. So realizing that a Mollier diagram is essentially a Psychrometric Chart (or Carrier Diagram, according to the Wikipedia article!) mirrored on `x=y`, what I'm doing here is adding an additional option to flip X and Y.

Screenshot 2024-04-17 at 2 56 37 PM

Here's a screenshot of the final product. This might not be *exactly* what you're looking for, but it leverages a lot of the existing logic and code to make what I think is a rather elegant solution. I'm still working on cleaning it up and I hope to push it live in the next week or so. Is this something that you think will be useful for you?

**Comment by yevgeny7** [comment]
@6nv Oh that looks already pretty familiar, flipping is already the most important move. Nice!
I have noticed, in the options you can select SI units, which is really great. 

A few more changes should make it really useful to EU people: 

no. 1 (prio 1): As vertical lines, with units on top, the EU version shows the absolute humidity (0 g/kg ... 20 g/kg) instead of the wet bulb temp (e.g. 90 °F) in the flipped psychart.

no 2 (prio 2): As diagonal lines, with units along at the wet bulb curve, the EU version shows the enthalpy (0 kJ/kg ... 60 kJ/kg) instead of the the wet bulb temp (20 °F ... 90 °F).

no. 3 (prio 1): data: as raw data we usually have dry bulb in °C and relative humidity (%). that would be rather helpful to use these values directly as input, and avoid additional pre calculation from °C to °F.

no. 4 (prio 2): comfort regions/envelope: of course we have other envelopes than included. I don't think you need to set EU envelopes, or any other, precoded by you. Because there is just too many. It would be a very powerful feature if the user could set individual envelopes by putting in the boundary conditions. An envelope consists of 4 to 6 corner points and the connection between them, straight connection or along some static value like relative humidity.

Sorry if it is a lot too ask. :-)

**Comment by 6nv** [comment]
@yevgeny7 - good news, your item (no. 3) is already a feature! If your data is in Celsius, simply toggle this option. No unit conversion needed:

Screenshot 2024-04-18 at 7 54 40 AM

Your item (no. 4) might also exist already if I understand it correctly. When you switch from US to SI units, the regions will re-calculate in the proper unit. If there are additional envelopes you would like to see added in Psychart, please let me know! That is easy to implement.

As for items (no. 1) and (no. 2), that would fundamentally change how I build and render Psychart and would be a long term project. However, there exists a feature that you may be interested in, to show "advanced" state variables. When enabled, you can hover over a point to see absolute humidity (called Hum. Ratio) and enthalpy. Of course, these numbers will be calculated in SI units when selected.

adv

Let me know if these features help you achieve your goal!

**Comment by 6nv** [comment]
@yevgeny7 - [Psychart v4.3.0](https://grafana.com/grafana/plugins/ventura-psychrometric-panel/?tab=overview) is available for installation.

**Comment by brngates98** [comment]
looking for ability to modify the axis i want to replicate a chart found in the meraki dashboards
Screenshot 2024-06-18 at 12 36 37 PM

**Comment by 6nv** [comment]
Hi @brngates98 and thanks for your suggestion! The only difference I can spot between this one and Psychart is the y-axis is plotted in humidity ratio instead of dew point - is this your request?

**Comment by brngates98** [comment]
@6nv  essentially yes, just ability to customize the axis's and such

**Comment by 6nv** [comment]
Psychart does give the ability to modify axes using these fields:

- Unit system (degrees C or F)
- Minimum dry bulb temperature (x-axis min)
- Maximum dry bulb temperature (x-axis max)
- Maximum dew point temperature (y-axis max)

Is this what you're looking for, @brngates98?

Screenshot 2024-06-20 at 12 46 19 PM

**Comment by ashharrison90** [comment]
Hi from the Grafana team 👋 

In Grafana 12, we'll be [removing Angular support](https://grafana.com/blog/2024/03/11/removal-of-angularjs-support-in-grafana-what-you-need-to-know/). As part of that, we'll also be removing a lot of legacy CSS classes.
It looks like this plugin relies on one of these classes:
- `panel-empty`

The CSS class names that Grafana provides can change at any time and should not be relied on as a stable external API. The recommendation would be to either:
- Use an existing component from the component library at `@grafana/ui`
- [Use the theme object with emotion](https://github.com/grafana/grafana/blob/main/contribute/style-guides/styling.md) to style your components. The theme object is a stable API that is maintained according to SemVer. 
- Apply these styles yourself within this repo. You can find the existing styles [here](https://github.com/grafana/grafana/blob/main/public/sass/_angular.scss) as a reference.

Thanks again for your contributions and support! 🙌

**Comment by brngates98** [comment]
@6nv well i would like to be able to do the following:

plot in humidity ratio instead of dew point
ability to remove wet bulb when not defined

**Comment by 6nv** [comment]
@ashharrison90 - thank you for the information. This will be fixed in the next patch version of Psychart: [v4.3.2](https://github.com/nicfv/Psychart/releases/tag/v4.3.2).

@brngates98 - thank you for your request. I will likely work on this in a future version of Psychart. For now, I recommend checking the box labeled "show advanced state variables" which will display humidity ratio when hovering the mouse over your data points.

**Comment by mofassair** [comment]
Hi,
@6nv waiting for your update on the v4.3.2.
I caould mange to shape the panel but stuck at two points. 
image
1) on the top x axis we need absolute humidity 
2) we need comfort region. Understand, there might be hundreds of region depending upon demand. So, might be an option to draw the region or DIN33404 is at the moment what i need. we need a region like below. 
image
option would be nice.

**Comment by 6nv** [comment]
Hi @mofassair , thank you for your suggestions. For item 2, do you have a source/list of psychrometric regions that you would like to see rendered on the chart?

**Comment by raph-topo** [comment]
Hi, thanks a lot for having developed this great plugin!

I started looking into adding the Givoni Building Bioclimatic Chart regions, e.g. https://drajmarsh.bitbucket.io/psychro-chart2d.html select Comfort Overlay : Givoni Bioclimatic Chart.

Because the regions are static, my first thought was to create 3: `'Givoni (Summer)' | 'Givoni (Spring/Autumn)' | 'Givoni (Winter)'` with mean outdoor temp of 24°C, 16°C, 8°C respectively. But that's already very specific. Would there be any way in which to create dynamic regions (as in the e.g. above)?

Sources: Olgyay 1963, Milne and Givoni 1979, Watson and Labs 1983.
More info: https://andrewmarsh.com/software/psychro-chart-web/#comfort-overlays & https://oaktrust.library.tamu.edu/handle/1969.1/ETD-TAMU-2015 (p. 22-23, 63)

Would you be so kind as to explain how to understand (& configure)
```ts
// psychart.ts
            data: [
                { db: 5, other: -12, measurement: 'dbdp' },
                { db: 22.5, other: 0.08, measurement: 'dbrh' },
                { db: 45.0, other: 0.08, measurement: 'dbrh' },
                { db: 45.0, other: 24, measurement: 'dbdp' },
                { db: 25.8, other: 0.90, measurement: 'dbrh' },
                { db: 5, other: 0.90, measurement: 'dbrh' },
            ],
```

**Comment by 6nv** [comment]
@raph-topo thank you for using Psychart and for your contribution! This is interesting, I am personally not familiar with these bioclimactic regions, do you know what country where they are primarily used? If this is widely used, then I would be interested in implementing it directly into Psychart itself.

Adding additional (static) regions to Psychart should be fairly simple and you are on the right track. At this time, there is no functionality to create dynamic regions although it was something I had thought about.

---

***For creating your own custom region***

Region names are defined here:

https://github.com/nicfv/Psychart/blob/f2b5f13899de254d74825060d0c332a004a132f0/src/types.ts#L4

And region data is defined here:

https://github.com/nicfv/Psychart/blob/f2b5f13899de254d74825060d0c332a004a132f0/src/psychart.ts#L45-L54

Follow the style shown (or read the object definition in `types.ts`). Region data expects an array of psychrometric states in clockwise (or counterclockwise) order. In region data, `db` is the dry-bulb value and `other` can either be wet bulb, dew point, or relative humidity, depending on `measurement`.

**Comment by raph-topo** [comment]
Thanks for your quick answer and tips!
After trying various configurations for that comfort region, I figured one single comfort zone covers all-year.
And here it is: #15 
Tested:
image
Congratulations for the best test&build setup I've seen in a long time!

**Comment by 6nv** [comment]
@raph-topo that was quick! I'll clone your repo and test it out tonight or within the next day or so, but from your screenshot, it looks good. Re: Test-build setup, I have [Grafana](https://grafana.com/developers/plugin-tools/) to thank for that one, I just used their tools provided.

**Comment by raph-topo** [comment]
Great, thanks!
Here's for a real-life example on my instance:
image
That makes me think: would there be a way to give more options for graphics? I.e. : only border of the region, colours like most other panels?
image

**Comment by raph-topo** [comment]
Actually, here's one as I imagined it: 
image
https://github.com/nicfv/Psychart/compare/main...raph-topo:Psychart:style
But it is hard-coded style still, would need to get a selection box etc.

**Comment by raph-topo** [comment]
> we could add more regions (e.g. natural ventilation.)

Yes, absolutely, that would be awesome. Only thing to consider is, that current regions (ASHRAE & Givoni Comfort) are valid for representing indoor climate, whereas the rest of the "Givoni" Building Bioclimatic Chart is for representing outdoor climate and choosing a bioclimatic strategy based on that. I think there should be a distinction between the two types somehow (an informational note? or a toggle between two sets of zones? or we don't care and it's up to the person making the graph?)

**Comment by thomasbromkapsdata** [comment]
Exactly the same request
> Speaking of colours, I'd also be favourable of having the choice of monochrome (single color instead of gradient). E.g. to represent outdoor climate as a light gray veil behind indoor data.
In many situation i feel that single color will be better than gradient now that the plugin provide multiple series option.

**Comment by nicfv** [comment]
@thomasbromkapsdata and @raph-topo - thanks for your request. I actually didn't see it (or maybe I just forgot) but I can see this being a very useful feature. Psychart was originally designed to render time-series data, but as I am gathering, not everyone uses it for that purpose, so monochrome color series could make a lot of sense to display thermodynamic processes.

## Update:

I'm working on porting Psychart's source code to NPM. Any further bug reports, questions, or feature requests should be issued here:

https://github.com/nicfv/npm/issues

Lastly, here is the **in-progress** npm package. Use `npm i psychart` to install it in a nodejs project.

https://www.npmjs.com/package/psychart

**Comment by nicfv** [comment]
Clarification: This issues page remains open for issues relating to the Grafana plugin. Issues relating to Psychart itself should be addressed in that new repository.

**Comment by Xiaoyulalala** [comment]
## Error: Cannot modify the Temperature in Axis Intervals
- Grafana Version: 10.2.9
- Psychart Plugin Version: 5.0.0 
截屏2025-05-19 15 26 47

Every time I modify the Temperature in Axis Intervals, the panel reports an error.
 
截屏2025-05-19 15 37 50
截屏2025-05-19 15 24 31

**Comment by nagisa** [comment]
Any chance this panel could be extended to accept the atmospheric pressure as a series rather than hard-coding via a altitude from sea level? Not a big deal, just felt odd having to specify a fixed altitude when I have the measured atmospheric pressure data itself.

Thank you for this amazing visualization!

**Comment by 6nv** [comment]
> Any chance this panel could be extended to accept the atmospheric pressure as a series rather than hard-coding via a altitude from sea level? Not a big deal, just felt odd having to specify a fixed altitude when I have the measured atmospheric pressure data itself.

Interesting request, I hadn't considered this one before.

I'm not sure a varying series would work, because the visualization (chart) itself depends on a constant atmospheric pressure in order to calculate and render the iso-wet bulb lines, for example.

However you make a good point that instead of accepting the elevation, I could make it a toggle switch between elevation or accepting a value for pressure directly. I won't have time to work on this for a little while at least; but PRs are welcome!

> Thank you for this amazing visualization!

You're welcome, and thank you as well! It's people like you that help keep these projects thriving!

**Pull request closed without merging**
